// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ7s-FQf8XhprgUBUCtDaY96nqsDZc6zo',
    appId: '1:219340262668:web:ae824c451d3b814c11cd29',
    messagingSenderId: '219340262668',
    projectId: 'parku-93437',
    authDomain: 'parku-93437.firebaseapp.com',
    storageBucket: 'parku-93437.appspot.com',
    measurementId: 'G-Y3RL8WXGCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYkJcBHj3jYefs3pf0PUcsNsX1yHWYeBc',
    appId: '1:219340262668:android:99e70791bad868f311cd29',
    messagingSenderId: '219340262668',
    projectId: 'parku-93437',
    storageBucket: 'parku-93437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLO4n0wNAwu6Pp214G5poVRu4aVQ0Y9g',
    appId: '1:219340262668:ios:0835ed62df6e7b6b11cd29',
    messagingSenderId: '219340262668',
    projectId: 'parku-93437',
    storageBucket: 'parku-93437.appspot.com',
    iosClientId: '219340262668-eie3tdtpol80jib2fg560jsr7jfvuujo.apps.googleusercontent.com',
    iosBundleId: 'com.example.parku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCLO4n0wNAwu6Pp214G5poVRu4aVQ0Y9g',
    appId: '1:219340262668:ios:0835ed62df6e7b6b11cd29',
    messagingSenderId: '219340262668',
    projectId: 'parku-93437',
    storageBucket: 'parku-93437.appspot.com',
    iosClientId: '219340262668-eie3tdtpol80jib2fg560jsr7jfvuujo.apps.googleusercontent.com',
    iosBundleId: 'com.example.parku',
  );
}
